# Generated by Django 4.2.5 on 2025-04-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_procedimiento', models.CharField(choices=[('via_publica', 'Vía pública'), ('cuartel_policial', 'Cuartel policial'), ('domicilio', 'Domicilio particular'), ('empresa', 'Empresa'), ('otro', 'Otro')], max_length=50)),
                ('fecha_ocurrencia', models.DateField()),
                ('hora_ocurrencia', models.TimeField()),
                ('fecha_denuncia', models.DateField()),
                ('hora_denuncia', models.TimeField()),
                ('funcionaria_codigo', models.CharField(max_length=50)),
                ('funcionaria_rut', models.CharField(max_length=20)),
                ('modo_operandi', models.TextField(blank=True, null=True)),
                ('delito_tipificado', models.CharField(max_length=255)),
                ('otros_delitos_observados', models.TextField(blank=True, null=True)),
                ('es_violencia_intrafamiliar', models.BooleanField(default=False)),
                ('victima_mujer_presente_guardia', models.BooleanField(default=False)),
                ('es_accidente_transito', models.BooleanField(default=False)),
                ('tipo_lugar', models.CharField(choices=[('via_publica', 'Vía pública'), ('cuartel_policial', 'Cuartel policial'), ('domicilio', 'Domicilio particular'), ('empresa', 'Empresa'), ('otro', 'Otro')], max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('block', models.CharField(blank=True, max_length=10)),
                ('villa', models.CharField(blank=True, max_length=100)),
                ('depto', models.CharField(blank=True, max_length=10)),
                ('km', models.CharField(blank=True, max_length=10)),
                ('interseccion', models.CharField(blank=True, max_length=255)),
                ('narracion_hechos', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
