# Generated by Django 4.2.5 on 2025-04-18 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventopolicial',
            name='delito_tipificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.delito'),
        ),
    ]
