# Generated by Django 4.2.5 on 2025-04-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_eventopolicial_delito_tipificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopolicial',
            name='numero_evento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
