# Generated by Django 4.2.5 on 2025-04-19 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eventopolicial_numero_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=12)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('calidad', models.CharField(choices=[('victima', 'Víctima'), ('imputado', 'Imputado'), ('testigo', 'Testigo'), ('otro', 'Otro')], max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('numero_calle', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.eventopolicial')),
            ],
        ),
    ]
