# Generated by Django 4.2.5 on 2025-04-24 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_especie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartePolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parte', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parte_policial', to='core.eventopolicial')),
            ],
        ),
    ]
