# Generated by Django 4.2.5 on 2025-04-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_partepolicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopolicial',
            name='estado_validacion',
            field=models.CharField(choices=[('en_edicion', 'En edición'), ('en_validacion', 'En validación'), ('parte_generado', 'Parte generado'), ('enviado_fiscalia', 'Enviado a Fiscalía')], default='en_edicion', max_length=50),
        ),
    ]
