# Generated by Django 4.2.5 on 2025-05-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_eventopolicial_estado_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='partepolicial',
            name='fiscalia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='calidad',
            field=models.CharField(choices=[('victima', 'Víctima'), ('imputado', 'Imputado'), ('testigo', 'Testigo'), ('denunciante_victima', 'Denunciante/Víctima'), ('otro', 'Otro')], max_length=50),
        ),
    ]
