# Generated by Django 4.2.5 on 2025-05-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_partepolicial_fiscalia_alter_participante_calidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopolicial',
            name='firma_denunciante',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='eventopolicial',
            name='firma_funcionario',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='eventopolicial',
            name='origen',
            field=models.CharField(choices=[('web', 'Web'), ('app', 'App')], default='web', max_length=10),
        ),
    ]
