# Generated by Django 4.2.5 on 2025-06-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tipolugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
