# Generated by Django 4.2.5 on 2025-07-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_participante_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventopolicial',
            name='funcionaria_codigo',
            field=models.CharField(max_length=50, verbose_name='Funcionario código'),
        ),
        migrations.AlterField(
            model_name='eventopolicial',
            name='funcionaria_rut',
            field=models.CharField(max_length=20, verbose_name='Funcionario rut'),
        ),
    ]
