# Generated by Django 4.2.5 on 2025-08-12 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_eventopolicial_funcionaria_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadPolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_policiales', to='core.comuna')),
            ],
        ),
    ]
