# Generated by Django 4.2.5 on 2025-08-20 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_unidadpolicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopolicial',
            name='unidad_policial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unidadpolicial'),
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_activa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidadpolicial')),
            ],
        ),
    ]
