# Generated by Django 4.2.5 on 2025-09-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_eventopolicial_unidad_policial_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventopolicial',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventopolicial',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
