# Generated by Django 4.2.5 on 2025-11-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_eventopolicial_lat_eventopolicial_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('correo', models.EmailField(max_length=255)),
            ],
        ),
    ]
