# Generated by Django 4.2.5 on 2025-11-14 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_fiscalia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEnvioFiscalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscalia_nombre', models.CharField(max_length=255)),
                ('fiscalia_correo', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado correctamente'), ('error', 'Error en envío')], max_length=20)),
                ('mensaje_respuesta', models.TextField(blank=True, null=True)),
                ('gmail_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partepolicial')),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
