# Generated by Django 4.2.5 on 2025-11-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_historialenviofiscalia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialenviofiscalia',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Historial de Envío a Fiscalía', 'verbose_name_plural': 'Historial de Envíos a Fiscalía'},
        ),
        migrations.AddField(
            model_name='historialenviofiscalia',
            name='codigo_auditoria',
            field=models.CharField(default='POR-DEFINIR', editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
