# Generated by Django 4.2.5 on 2025-05-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('administrador', 'Administrador'), ('oficial_guardia', 'oficial_guardia'), ('funcionario', 'Funcionario')], max_length=20),
        ),
    ]
