# Generated by Django 4.2.5 on 2025-05-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rut',
            field=models.CharField(default='00000000-0', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
