# Generated by Django 4.2.5 on 2025-05-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_perfilusuario_rut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
