# Generated by Django 4.2.5 on 2025-06-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_delete_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cambio_password_obligado',
            field=models.BooleanField(default=True),
        ),
    ]
