# Generated by Django 4.2.5 on 2025-06-26 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0006_perfilusuario_cambio_password_obligado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_ultimo_cambio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
