# Generated by Django 4.2.5 on 2025-08-20 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_unidadpolicial'),
        ('funcionarios', '0007_perfilusuario_fecha_ultimo_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='unidad_policial',
            field=models.ForeignKey(blank=True, help_text='Unidad a la que pertenece el usuario (comisaría)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidadpolicial'),
        ),
    ]
