# Generated by Django 4.2.5 on 2025-05-06 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfraccionTransito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_infraccion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('region', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('block', models.CharField(blank=True, max_length=20, null=True)),
                ('villa', models.CharField(blank=True, max_length=100, null=True)),
                ('depto', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteInfraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('Station Wagon', 'Station Wagon'), ('Hatchback', 'Hatchback'), ('Sedán', 'Sedán'), ('Coupé', 'Coupé'), ('Camioneta', 'Camioneta'), ('SUV', 'SUV'), ('Van', 'Van'), ('Minivan', 'Minivan'), ('City Car', 'City Car'), ('Eléctrico/Híbrido', 'Eléctrico/Híbrido')], max_length=30)),
                ('color', models.CharField(choices=[('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Gris', 'Gris'), ('Plateado', 'Plateado'), ('Verde', 'Verde'), ('Amarillo', 'Amarillo'), ('Naranja', 'Naranja'), ('Café', 'Café'), ('Burdeo', 'Burdeo'), ('Beige', 'Beige'), ('Celeste', 'Celeste'), ('Dorado', 'Dorado'), ('Otro', 'Otro')], max_length=20)),
                ('placa_patente', models.CharField(max_length=10)),
                ('chasis', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('infraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='infracciones.infracciontransito')),
            ],
        ),
    ]
