# Generated by Django 4.2.5 on 2025-05-06 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infracciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracciontransito',
            name='tipo_infraccion',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='ParteInfraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parte', models.CharField(max_length=20, unique=True)),
                ('juzgado', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('infraccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parte', to='infracciones.infracciontransito')),
            ],
        ),
    ]
