# Generated by Django 4.2.5 on 2025-05-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infracciones', '0003_participanteinfraccion_calidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infracciontransito',
            name='boleta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infracciontransito',
            name='fecha_denuncia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infracciontransito',
            name='funcionario_codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='infracciontransito',
            name='hora_denuncia',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
